export type Lang = "en" | "km";

const COPY = {
  catalog: { en: "Catalogue", km: "កាតាឡុក" },
  catalog_add_title: { en: "Add products to your catalogue", km: "បន្ថែមផលិតផលទៅកាតាឡុក" },
  catalog_add_sub: { en: "Choose how you want to add them", km: "ជ្រើសរើសវិធីបន្ថែម" },
  choose_method: { en: "CHOOSE A METHOD", km: "ជ្រើសរើសវិធី" },
  method_list: { en: "Select from list", km: "ជ្រើសពីបញ្ជី" },
  method_list_desc: {
    en: "Pick from the most common materials in Cambodia. Fast setup for new stores.",
    km: "ជ្រើសពីសម្ភារៈពេញនិយមក្នុងកម្ពុជា។ ងាយស្រួលសម្រាប់ហាងថ្មី។",
  },
  recommended_first: { en: "Recommended for first time", km: "ណែនាំសម្រាប់លើកដំបូង" },
  method_import: { en: "Import from file or photo", km: "នាំចូលពីឯកសារ ឬរូបថត" },
  method_import_desc: {
    en: "Upload your price list — Excel, photo, PDF or WhatsApp. AI converts it automatically.",
    km: "បញ្ចូលបញ្ជីតម្លៃ — Excel, រូបថត, PDF ឬ WhatsApp។ AI បំលែងស្វ័យប្រវត្តិ។",
  },
  method_photo: { en: "Photo of product", km: "រូបថតផលិតផល" },
  method_photo_desc: {
    en: "Take a photo and AI fills in the details. Best for adding individual items.",
    km: "ថតរូប ហើយ AI បំពេញព័ត៌មាន។ ល្អសម្រាប់បន្ថែមម្តងមួយ។",
  },
  methods_note: {
    en: "You can use all three methods at any time. Start with the list, then add new products by photo as they arrive.",
    km: "អ្នកអាចប្រើវិធីទាំងបីពេលណាក៏បាន។ ចាប់ផ្តើមពីបញ្ជី បន្ទាប់មកបន្ថែមតាមរូបថត។",
  },
  already_in_catalog: { en: "Already in your catalogue", km: "មានក្នុងកាតាឡុករួចហើយ" },
  continue: { en: "Continue", km: "បន្ត" },
  step_of: { en: "Step {n} of 3", km: "ជំហាន {n} ក្នុង ៣" },
  step1_title: { en: "Choose your categories", km: "ជ្រើសប្រភេទរបស់អ្នក" },
  step1_sub: {
    en: "Tap all the categories you carry. We'll show you the most common products for each one.",
    km: "ចុចលើប្រភេទទាំងអស់ដែលអ្នកមាន។ យើងបង្ហាញផលិតផលពេញនិយមនីមួយៗ។",
  },
  step2_title: { en: "Mark what you have", km: "ធីកអ្វីដែលអ្នកមាន" },
  step2_sub: {
    en: "Tap each product you sell and set your price. Price is optional.",
    km: "ចុចផលិតផលដែលអ្នកលក់ ហើយដាក់តម្លៃ។ តម្លៃមិនចាំបាច់។",
  },
  step3_title: { en: "Review and publish", km: "ពិនិត្យ និងបង្ហោះ" },
  step3_sub: { en: "Check your products before saving.", km: "ពិនិត្យផលិតផលមុនរក្សាទុក។" },
  products_count: { en: "products", km: "ផលិតផល" },
  selected_categories: { en: "categories selected", km: "ប្រភេទបានជ្រើស" },
  selected_products: { en: "products selected", km: "ផលិតផលបានជ្រើស" },
  save_catalog: { en: "Save to catalogue", km: "រក្សាទុកក្នុងកាតាឡុក" },
  saving: { en: "Saving…", km: "កំពុងរក្សាទុក…" },
  saved: { en: "Catalogue updated", km: "កាតាឡុកបានធ្វើបច្ចុប្បន្នភាព" },
  back: { en: "Back", km: "ត្រឡប់" },
  in_stock: { en: "In stock", km: "មានស្តុក" },
  out_of_stock: { en: "Out of stock", km: "អស់ស្តុក" },
  price: { en: "Price", km: "តម្លៃ" },
  unit: { en: "Unit", km: "ឯកតា" },
  upload_title: { en: "Import your price list", km: "នាំចូលបញ្ជីតម្លៃ" },
  upload_sub: {
    en: "Excel, CSV, PDF, a photo of handwritten paper or a WhatsApp screenshot — any format works.",
    km: "Excel, CSV, PDF, រូបថតក្រដាសសរសេរដៃ ឬ WhatsApp — គ្រប់ទម្រង់បាន។",
  },
  pick_file: { en: "Choose file or photo", km: "ជ្រើសឯកសារ ឬរូបថត" },
  reading_file: { en: "AI is reading your price list…", km: "AI កំពុងអានបញ្ជីតម្លៃ…" },
  import_found: { en: "products found", km: "ផលិតផលបានរកឃើញ" },
  import_failed: {
    en: "We couldn't read that file. Try a clearer photo or another format.",
    km: "យើងអានឯកសារនេះមិនបាន។ សាកល្បងរូបថតច្បាស់ជាង។",
  },
  import_empty: {
    en: "No products found in that file. Try a clearer photo.",
    km: "រកមិនឃើញផលិតផលក្នុងឯកសារនេះ។ សាកល្បងរូបថតច្បាស់ជាង។",
  },
  photo_title: { en: "Photograph a product", km: "ថតរូបផលិតផល" },
  photo_sub: {
    en: "AI identifies the name, category and description. You only confirm price and stock.",
    km: "AI កំណត់ឈ្មោះ ប្រភេទ និងការពិពណ៌នា។ អ្នកគ្រាន់តែបញ្ជាក់តម្លៃ និងស្តុក។",
  },
  take_photo: { en: "Take or choose a photo", km: "ថត ឬជ្រើសរូបថត" },
  identifying: { en: "AI is identifying the product…", km: "AI កំពុងកំណត់ផលិតផល…" },
  not_recognized: {
    en: "We couldn't identify that product. Try a closer photo.",
    km: "យើងកំណត់ផលិតផលនេះមិនបាន។ សាកល្បងថតជិតជាង។",
  },
  product_name: { en: "Product name", km: "ឈ្មោះផលិតផល" },
  category: { en: "Category", km: "ប្រភេទ" },
  description: { en: "Description", km: "ការពិពណ៌នា" },
  add_product: { en: "Add to catalogue", km: "បន្ថែមទៅកាតាឡុក" },
  my_catalog: { en: "My catalogue", km: "កាតាឡុករបស់ខ្ញុំ" },
  catalog_items: { en: "products in catalogue", km: "ផលិតផលក្នុងកាតាឡុក" },
  empty_catalog: { en: "No products yet", km: "មិនមានផលិតផលទេ" },
  remove: { en: "Remove", km: "លុប" },
  select_at_least_one: { en: "Select at least one item", km: "ជ្រើសយ៉ាងហោចមួយ" },
  no_products_for_category: {
    en: "No suggested products for this category yet — add them by photo or import.",
    km: "មិនមានផលិតផលស្នើសម្រាប់ប្រភេទនេះទេ — បន្ថែមតាមរូបថត ឬនាំចូល។",
  },
  step3_header: { en: "Set prices & stock", km: "កំណត់តម្លៃ និងស្តុក" },
  almost_done: { en: "Almost done", km: "ជិតរួចរាល់" },
  step3_section: { en: "STEP 3 — PRICES & AVAILABILITY", km: "ជំហាន ៣ — តម្លៃ និងស្តុក" },
  set_your_prices: { en: "Set your prices", km: "កំណត់តម្លៃរបស់អ្នក" },
  set_your_prices_sub: {
    en: "Add a photo, set your price and stock. Photo is optional — AI fills details automatically.",
    km: "បន្ថែមរូបថត កំណត់តម្លៃ និងស្តុក។ រូបថតមិនចាំបាច់ — AI បំពេញព័ត៌មានស្វ័យប្រវត្តិ។",
  },
  your_price: { en: "Your price", km: "តម្លៃរបស់អ្នក" },
  availability: { en: "Availability", km: "ស្តុក" },
  low_stock: { en: "Low", km: "តិច" },
  out_label: { en: "Out", km: "អស់" },
  market_range: { en: "Market range", km: "ចន្លោះតម្លៃទីផ្សារ" },
  product_photo: { en: "Product photo", km: "រូបថតផលិតផល" },
  photo_hint: {
    en: "Upload a photo — AI will fill name and description.",
    km: "បញ្ចូលរូបថត — AI នឹងបំពេញឈ្មោះ និងការពិពណ៌នា។",
  },
  photo_hint_done: {
    en: "AI auto-fills name and description from your photo.",
    km: "AI បំពេញឈ្មោះ និងការពិពណ៌នាពីរូបថតរបស់អ្នក។",
  },
  photo_added: { en: "Photo added", km: "បានបន្ថែមរូបថត" },
  add_photo: { en: "Add photo", km: "បន្ថែមរូបថត" },
  added: { en: "Added", km: "បានបន្ថែម" },
  autofilled_tap_edit: { en: "Auto-filled · tap to edit", km: "បំពេញស្វ័យប្រវត្តិ · ចុចដើម្បីកែ" },
  optional: { en: "Optional", km: "មិនចាំបាច់" },
  catalog_ready: { en: "Catalogue ready", km: "កាតាឡុករួចរាល់" },
  publish_catalog: { en: "Publish catalogue", km: "បង្ហោះកាតាឡុក" },
  category_one: { en: "category", km: "ប្រភេទ" },
  my_catalogue: { en: "My catalogue", km: "កាតាឡុករបស់ខ្ញុំ" },
  manage_catalog: { en: "Manage catalogue", km: "គ្រប់គ្រងកាតាឡុក" },
  manage_catalog_desc: {
    en: "See views, requests, market prices and update stock.",
    km: "មើលការមើល សំណើ តម្លៃទីផ្សារ និងកែស្តុក។",
  },
  total_products: { en: "Total products", km: "ផលិតផលសរុប" },
  across_categories: { en: "across {n} categories", km: "ក្នុង {n} ប្រភេទ" },
  requests_this_week: { en: "Requests this week", km: "សំណើសប្តាហ៍នេះ" },
  vs_last_week_up: { en: "{n} more than last week", km: "ច្រើនជាងសប្តាហ៍មុន {n}" },
  vs_last_week_down: { en: "{n} less than last week", km: "តិចជាងសប្តាហ៍មុន {n}" },
  vs_last_week_same: { en: "same as last week", km: "ដូចសប្តាហ៍មុន" },
  in_stock_card: { en: "In stock", km: "មានស្តុក" },
  out_of_stock_count: { en: "{n} out of stock", km: "អស់ស្តុក {n}" },
  most_requested: { en: "Most requested", km: "ស្នើសុំច្រើនបំផុត" },
  requests_this_week_short: { en: "{n} requests this week", km: "សំណើ {n} សប្តាហ៍នេះ" },
  stock_alert: {
    en: "{name} is out of stock. {n} users searched for it this week. Update when available.",
    km: "{name} អស់ស្តុក។ អ្នកប្រើ {n} បានស្វែងរកសប្តាហ៍នេះ។ សូមកែពេលមានវិញ។",
  },
  most_searched_week: { en: "Most searched this week", km: "ស្វែងរកច្រើនបំផុតសប្តាហ៍នេះ" },
  no_market_data: { en: "No search data yet this week.", km: "មិនទាន់មានទិន្នន័យស្វែងរក។" },
  products_label: { en: "PRODUCTS", km: "ផលិតផល" },
  sort_by_requests: { en: "Sort by requests", km: "តាមសំណើ" },
  sort_by_name: { en: "Sort by name", km: "តាមឈ្មោះ" },
  all_label: { en: "All", km: "ទាំងអស់" },
  views_short: { en: "Views", km: "ការមើល" },
  chats_short: { en: "Chats", km: "ឆាត" },
  vs_market: { en: "vs market", km: "ធៀបទីផ្សារ" },
  on_range: { en: "on range", km: "ក្នុងចន្លោះ" },
  no_market: { en: "no market data", km: "គ្មានទិន្នន័យ" },
  edit: { en: "Edit", km: "កែ" },
  offer: { en: "Offer", km: "បញ្ចុះតម្លៃ" },
  remove_confirm: { en: "Remove this product from your catalogue?", km: "លុបផលិតផលនេះពីកាតាឡុក?" },
  removed: { en: "Removed", km: "បានលុប" },
  internal_panel_note: {
    en: "Internal management panel — visible only to you",
    km: "ផ្ទាំងគ្រប់គ្រងផ្ទៃក្នុង — មានតែអ្នកឃើញ",
  },
  search_in_store: { en: "Search products in this store…", km: "ស្វែងរកផលិតផលក្នុងហាងនេះ…" },
  filter_label: { en: "Filter", km: "ត្រង" },
  sort_available_first: { en: "Available first", km: "មានស្តុកមុន" },
  sort_price_low: { en: "Price: low to high", km: "តម្លៃ៖ ទាបទៅខ្ពស់" },
  sort_price_high: { en: "Price: high to low", km: "តម្លៃ៖ ខ្ពស់ទៅទាប" },
  ask: { en: "Ask", km: "សួរ" },
  ask_price: { en: "Ask for price", km: "សួរតម្លៃ" },
  notify_me: { en: "Notify me", km: "ជូនដំណឹង" },
  notify_on: { en: "Will notify", km: "នឹងជូនដំណឹង" },
  notify_saved: {
    en: "We'll notify you when it's back in stock",
    km: "យើងនឹងជូនដំណឹងពេលមានស្តុកវិញ",
  },
  no_results: { en: "No products match your search", km: "រកមិនឃើញផលិតផល" },
  store_catalog: { en: "Products", km: "ផលិតផល" },
  fast_response: { en: "Fast response", km: "ឆ្លើយតបលឿន" },
  delivery_available: { en: "Delivery available", km: "មានដឹកជញ្ជូន" },
  min_order: { en: "Min. {v}", km: "អប្បបរមា {v}" },
  call: { en: "Call", km: "ហៅ" },
  location: { en: "Location", km: "ទីតាំង" },
  chat: { en: "Chat", km: "ឆាត" },
  my_stats: { en: "My stats", km: "ស្ថិតិរបស់ខ្ញុំ" },
  view_stats: { en: "View stats", km: "មើលស្ថិតិ" },
  period_7d: { en: "7 days", km: "៧ ថ្ងៃ" },
  period_month: { en: "This month", km: "ខែនេះ" },
  period_3m: { en: "3 months", km: "៣ ខែ" },
  profile_views: { en: "Profile views", km: "ការមើលទំព័រ" },
  material_requests: { en: "Material requests", km: "សំណើសម្ភារៈ" },
  chats_started: { en: "Chats started", km: "ឆាតបានចាប់ផ្តើម" },
  response_rate: { en: "Response rate", km: "អត្រាឆ្លើយតប" },
  vs_last_period: { en: "{v} vs last period", km: "{v} ធៀបរយៈពេលមុន" },
  from_requests: { en: "from {n} requests", km: "ក្នុងសំណើ {n}", },
  above_average: { en: "Above average", km: "លើសមធ្យម" },
  below_average: { en: "Below average", km: "ក្រោមមធ្យម" },
  requests_per_day: { en: "Requests per day", km: "សំណើក្នុងមួយថ្ងៃ" },
  most_requested_products: { en: "Most requested products", km: "ផលិតផលស្នើសុំច្រើន" },
  search_gaps: { en: "Searched but not in your catalogue", km: "គេស្វែងរក តែអ្នកគ្មាន" },
  opportunity: { en: "Opportunity", km: "ឱកាស" },
  attention: { en: "Attention", km: "ចំណាំ" },
  opportunity_text: {
    en: "{term} searched {n} times this period near your store. No supplier in your area has it right now.",
    km: "{term} ត្រូវបានស្វែងរក {n} ដងក្នុងរយៈពេលនេះជិតហាងអ្នក។ គ្មានអ្នកផ្គត់ផ្គង់ណាមានទេ។",
  },
  attention_text: {
    en: "{name} is out of stock but received {n} requests. Update stock when available.",
    km: "{name} អស់ស្តុក តែមានសំណើ {n}។ សូមកែពេលមានវិញ។",
  },
  no_stats_yet: { en: "No data for this period yet.", km: "មិនទាន់មានទិន្នន័យ។" },
  today_label: { en: "Today", km: "ថ្ងៃនេះ" },
  stock_updated: { en: "Stock updated {v}", km: "ស្តុកកែ {v}" },
  report_issue: { en: "Report", km: "រាយការណ៍" },
  report_title: { en: "Report a problem", km: "រាយការណ៍បញ្ហា" },
  report_hint: {
    en: "Only BuildHub sees this. The supplier is never notified.",
    km: "មានតែ BuildHub ឃើញ។ អ្នកផ្គត់ផ្គង់មិនដឹងទេ។",
  },
  report_reason_unavailable: { en: "Not available on arrival", km: "ទៅដល់គ្មានទំនិញ" },
  report_reason_price: { en: "Price was different", km: "តម្លៃខុសពីបង្ហាញ" },
  report_reason_closed: { en: "Store was closed", km: "ហាងបិទ" },
  report_reason_other: { en: "Other", km: "ផ្សេងទៀត" },
  report_note_placeholder: { en: "Add a detail (optional)", km: "បន្ថែមព័ត៌មាន (ស្រេចចិត្ត)" },
  report_send: { en: "Send report", km: "ផ្ញើរាយការណ៍" },
  report_sent: { en: "Thanks — BuildHub received your report.", km: "អរគុណ — BuildHub ទទួលបានហើយ។" },
  report_already: { en: "You already reported this today.", km: "អ្នករាយការណ៍រួចហើយថ្ងៃនេះ។" },
  report_login: { en: "Sign in to report a problem.", km: "ចូលគណនីដើម្បីរាយការណ៍។" },
  cancel_label: { en: "Cancel", km: "បោះបង់" },
  on_offer: { en: "On offer", km: "កំពុងបញ្ចុះតម្លៃ" },
  offer_sheet_title: { en: "Flag as on offer", km: "ដាក់ស្លាកបញ្ចុះតម្លៃ" },
  offer_sheet_desc: {
    en: "The product keeps its place in your catalogue and shows an amber Offer tag to clients.",
    km: "ផលិតផលនៅតែក្នុងកាតាឡុក ហើយបង្ហាញស្លាកបញ្ចុះតម្លៃពណ៌លឿងដល់អតិថិជន។",
  },
  offer_price_label: { en: "Offer price (optional)", km: "តម្លៃបញ្ចុះ (ស្រេចចិត្ត)" },
  offer_activate: { en: "Activate offer", km: "បើកការបញ្ចុះតម្លៃ" },
  offer_deactivate: { en: "Remove offer", km: "ដកការបញ្ចុះតម្លៃ" },
  offer_saved: { en: "Offer updated", km: "បានធ្វើបច្ចុប្បន្នភាព" },
  offer_feed_note: {
    en: "Liquidations and time-limited deals are separate — post them in the feed. You don't need a catalogue for that.",
    km: "ការលក់សម្រាល និងការបញ្ចុះពេលកំណត់ ដាច់ដោយឡែក — ផ្សាយក្នុងព័ត៌មាន។ មិនត្រូវការកាតាឡុកទេ។",
  },
  offer_post_feed: { en: "Post a liquidation in the feed", km: "ផ្សាយការលក់សម្រាលក្នុងព័ត៌មាន" },
} as const;




export type CopyKey = keyof typeof COPY;

export function catalogCopy(lang: string, key: CopyKey): string {
  const entry = COPY[key];
  return lang === "km" ? entry.km : entry.en;
}
