/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnlineOrdersRouteImport } from './routes/online-orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FindWorkerRouteImport } from './routes/find-worker'
import { Route as FindMaterialRouteImport } from './routes/find-material'
import { Route as AnnounceRouteImport } from './routes/announce'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as SuppliersStoreIdRouteImport } from './routes/suppliers.$storeId'
import { Route as SuperuserPanelRouteImport } from './routes/superuser.panel'
import { Route as StoryViewRouteImport } from './routes/story.view'
import { Route as StoryNewRouteImport } from './routes/story.new'
import { Route as RentalsNewRouteImport } from './routes/rentals.new'
import { Route as RentalsRentalIdRouteImport } from './routes/rentals.$rentalId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProfilePortfolioRouteImport } from './routes/profile.portfolio'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'
import { Route as FindMaterialNewRouteImport } from './routes/find-material.new'
import { Route as FindMaterialMineRouteImport } from './routes/find-material.mine'
import { Route as AdminTelegramRouteImport } from './routes/admin.telegram'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminDrawsRouteImport } from './routes/admin.draws'
import { Route as SuppliersStoreIdEditRouteImport } from './routes/suppliers.$storeId.edit'
import { Route as SupplierJoinTokenRouteImport } from './routes/supplier.join.$token'
import { Route as RentalsRequestNewRouteImport } from './routes/rentals.request.new'
import { Route as ProjectsNewWorkerIdRouteImport } from './routes/projects.new.$workerId'
import { Route as ApiPublicTelegramNotifyRouteImport } from './routes/api/public/telegram-notify'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineOrdersRoute = OnlineOrdersRouteImport.update({
  id: '/online-orders',
  path: '/online-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FindWorkerRoute = FindWorkerRouteImport.update({
  id: '/find-worker',
  path: '/find-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMaterialRoute = FindMaterialRouteImport.update({
  id: '/find-material',
  path: '/find-material',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnounceRoute = AnnounceRouteImport.update({
  id: '/announce',
  path: '/announce',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersStoreIdRoute = SuppliersStoreIdRouteImport.update({
  id: '/suppliers/$storeId',
  path: '/suppliers/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperuserPanelRoute = SuperuserPanelRouteImport.update({
  id: '/superuser/panel',
  path: '/superuser/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryViewRoute = StoryViewRouteImport.update({
  id: '/story/view',
  path: '/story/view',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryNewRoute = StoryNewRouteImport.update({
  id: '/story/new',
  path: '/story/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsNewRoute = RentalsNewRouteImport.update({
  id: '/rentals/new',
  path: '/rentals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRentalIdRoute = RentalsRentalIdRouteImport.update({
  id: '/rentals/$rentalId',
  path: '/rentals/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePortfolioRoute = ProfilePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMaterialNewRoute = FindMaterialNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FindMaterialRoute,
} as any)
const FindMaterialMineRoute = FindMaterialMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => FindMaterialRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/admin/telegram',
  path: '/admin/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/admin/suppliers',
  path: '/admin/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/admin/invitations',
  path: '/admin/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDrawsRoute = AdminDrawsRouteImport.update({
  id: '/admin/draws',
  path: '/admin/draws',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersStoreIdEditRoute = SuppliersStoreIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SuppliersStoreIdRoute,
} as any)
const SupplierJoinTokenRoute = SupplierJoinTokenRouteImport.update({
  id: '/supplier/join/$token',
  path: '/supplier/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRequestNewRoute = RentalsRequestNewRouteImport.update({
  id: '/rentals/request/new',
  path: '/rentals/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewWorkerIdRoute = ProjectsNewWorkerIdRouteImport.update({
  id: '/projects/new/$workerId',
  path: '/projects/new/$workerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramNotifyRoute = ApiPublicTelegramNotifyRouteImport.update({
  id: '/api/public/telegram-notify',
  path: '/api/public/telegram-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/announce': typeof AnnounceRoute
  '/find-material': typeof FindMaterialRouteWithChildren
  '/find-worker': typeof FindWorkerRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/invitations': typeof InvitationsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/online-orders': typeof OnlineOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/draws': typeof AdminDrawsRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/find-material/mine': typeof FindMaterialMineRoute
  '/find-material/new': typeof FindMaterialNewRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/rentals/new': typeof RentalsNewRoute
  '/story/new': typeof StoryNewRoute
  '/story/view': typeof StoryViewRoute
  '/superuser/panel': typeof SuperuserPanelRoute
  '/suppliers/$storeId': typeof SuppliersStoreIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/public/telegram-notify': typeof ApiPublicTelegramNotifyRoute
  '/projects/new/$workerId': typeof ProjectsNewWorkerIdRoute
  '/rentals/request/new': typeof RentalsRequestNewRoute
  '/supplier/join/$token': typeof SupplierJoinTokenRoute
  '/suppliers/$storeId/edit': typeof SuppliersStoreIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/announce': typeof AnnounceRoute
  '/find-material': typeof FindMaterialRouteWithChildren
  '/find-worker': typeof FindWorkerRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/invitations': typeof InvitationsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/online-orders': typeof OnlineOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/draws': typeof AdminDrawsRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/find-material/mine': typeof FindMaterialMineRoute
  '/find-material/new': typeof FindMaterialNewRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/rentals/new': typeof RentalsNewRoute
  '/story/new': typeof StoryNewRoute
  '/story/view': typeof StoryViewRoute
  '/superuser/panel': typeof SuperuserPanelRoute
  '/suppliers/$storeId': typeof SuppliersStoreIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/listings': typeof ListingsIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/api/public/telegram-notify': typeof ApiPublicTelegramNotifyRoute
  '/projects/new/$workerId': typeof ProjectsNewWorkerIdRoute
  '/rentals/request/new': typeof RentalsRequestNewRoute
  '/supplier/join/$token': typeof SupplierJoinTokenRoute
  '/suppliers/$storeId/edit': typeof SuppliersStoreIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/announce': typeof AnnounceRoute
  '/find-material': typeof FindMaterialRouteWithChildren
  '/find-worker': typeof FindWorkerRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/invitations': typeof InvitationsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/online-orders': typeof OnlineOrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin/draws': typeof AdminDrawsRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/find-material/mine': typeof FindMaterialMineRoute
  '/find-material/new': typeof FindMaterialNewRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/rentals/$rentalId': typeof RentalsRentalIdRoute
  '/rentals/new': typeof RentalsNewRoute
  '/story/new': typeof StoryNewRoute
  '/story/view': typeof StoryViewRoute
  '/superuser/panel': typeof SuperuserPanelRoute
  '/suppliers/$storeId': typeof SuppliersStoreIdRouteWithChildren
  '/users/$userId': typeof UsersUserIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/api/public/telegram-notify': typeof ApiPublicTelegramNotifyRoute
  '/projects/new/$workerId': typeof ProjectsNewWorkerIdRoute
  '/rentals/request/new': typeof RentalsRequestNewRoute
  '/supplier/join/$token': typeof SupplierJoinTokenRoute
  '/suppliers/$storeId/edit': typeof SuppliersStoreIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/announce'
    | '/find-material'
    | '/find-worker'
    | '/help'
    | '/home'
    | '/invitations'
    | '/join'
    | '/login'
    | '/online-orders'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/report'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/terms'
    | '/admin/draws'
    | '/admin/invitations'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/admin/telegram'
    | '/find-material/mine'
    | '/find-material/new'
    | '/listings/$listingId'
    | '/listings/new'
    | '/messages/$threadId'
    | '/profile/edit'
    | '/profile/portfolio'
    | '/projects/$projectId'
    | '/rentals/$rentalId'
    | '/rentals/new'
    | '/story/new'
    | '/story/view'
    | '/superuser/panel'
    | '/suppliers/$storeId'
    | '/users/$userId'
    | '/listings/'
    | '/messages/'
    | '/suppliers/'
    | '/api/public/telegram-notify'
    | '/projects/new/$workerId'
    | '/rentals/request/new'
    | '/supplier/join/$token'
    | '/suppliers/$storeId/edit'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/announce'
    | '/find-material'
    | '/find-worker'
    | '/help'
    | '/home'
    | '/invitations'
    | '/join'
    | '/login'
    | '/online-orders'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/report'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/terms'
    | '/admin/draws'
    | '/admin/invitations'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/admin/telegram'
    | '/find-material/mine'
    | '/find-material/new'
    | '/listings/$listingId'
    | '/listings/new'
    | '/messages/$threadId'
    | '/profile/edit'
    | '/profile/portfolio'
    | '/projects/$projectId'
    | '/rentals/$rentalId'
    | '/rentals/new'
    | '/story/new'
    | '/story/view'
    | '/superuser/panel'
    | '/suppliers/$storeId'
    | '/users/$userId'
    | '/listings'
    | '/messages'
    | '/suppliers'
    | '/api/public/telegram-notify'
    | '/projects/new/$workerId'
    | '/rentals/request/new'
    | '/supplier/join/$token'
    | '/suppliers/$storeId/edit'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/announce'
    | '/find-material'
    | '/find-worker'
    | '/help'
    | '/home'
    | '/invitations'
    | '/join'
    | '/login'
    | '/online-orders'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/report'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/terms'
    | '/admin/draws'
    | '/admin/invitations'
    | '/admin/posts'
    | '/admin/reports'
    | '/admin/suppliers'
    | '/admin/telegram'
    | '/find-material/mine'
    | '/find-material/new'
    | '/listings/$listingId'
    | '/listings/new'
    | '/messages/$threadId'
    | '/profile/edit'
    | '/profile/portfolio'
    | '/projects/$projectId'
    | '/rentals/$rentalId'
    | '/rentals/new'
    | '/story/new'
    | '/story/view'
    | '/superuser/panel'
    | '/suppliers/$storeId'
    | '/users/$userId'
    | '/listings/'
    | '/messages/'
    | '/suppliers/'
    | '/api/public/telegram-notify'
    | '/projects/new/$workerId'
    | '/rentals/request/new'
    | '/supplier/join/$token'
    | '/suppliers/$storeId/edit'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnnounceRoute: typeof AnnounceRoute
  FindMaterialRoute: typeof FindMaterialRouteWithChildren
  FindWorkerRoute: typeof FindWorkerRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  InvitationsRoute: typeof InvitationsRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  OnlineOrdersRoute: typeof OnlineOrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AdminDrawsRoute: typeof AdminDrawsRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  RentalsRentalIdRoute: typeof RentalsRentalIdRoute
  RentalsNewRoute: typeof RentalsNewRoute
  StoryNewRoute: typeof StoryNewRoute
  StoryViewRoute: typeof StoryViewRoute
  SuperuserPanelRoute: typeof SuperuserPanelRoute
  SuppliersStoreIdRoute: typeof SuppliersStoreIdRouteWithChildren
  UsersUserIdRoute: typeof UsersUserIdRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  ApiPublicTelegramNotifyRoute: typeof ApiPublicTelegramNotifyRoute
  ProjectsNewWorkerIdRoute: typeof ProjectsNewWorkerIdRoute
  RentalsRequestNewRoute: typeof RentalsRequestNewRoute
  SupplierJoinTokenRoute: typeof SupplierJoinTokenRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-orders': {
      id: '/online-orders'
      path: '/online-orders'
      fullPath: '/online-orders'
      preLoaderRoute: typeof OnlineOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-worker': {
      id: '/find-worker'
      path: '/find-worker'
      fullPath: '/find-worker'
      preLoaderRoute: typeof FindWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-material': {
      id: '/find-material'
      path: '/find-material'
      fullPath: '/find-material'
      preLoaderRoute: typeof FindMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announce': {
      id: '/announce'
      path: '/announce'
      fullPath: '/announce'
      preLoaderRoute: typeof AnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$storeId': {
      id: '/suppliers/$storeId'
      path: '/suppliers/$storeId'
      fullPath: '/suppliers/$storeId'
      preLoaderRoute: typeof SuppliersStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superuser/panel': {
      id: '/superuser/panel'
      path: '/superuser/panel'
      fullPath: '/superuser/panel'
      preLoaderRoute: typeof SuperuserPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/view': {
      id: '/story/view'
      path: '/story/view'
      fullPath: '/story/view'
      preLoaderRoute: typeof StoryViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/new': {
      id: '/story/new'
      path: '/story/new'
      fullPath: '/story/new'
      preLoaderRoute: typeof StoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/new': {
      id: '/rentals/new'
      path: '/rentals/new'
      fullPath: '/rentals/new'
      preLoaderRoute: typeof RentalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$rentalId': {
      id: '/rentals/$rentalId'
      path: '/rentals/$rentalId'
      fullPath: '/rentals/$rentalId'
      preLoaderRoute: typeof RentalsRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/portfolio': {
      id: '/profile/portfolio'
      path: '/portfolio'
      fullPath: '/profile/portfolio'
      preLoaderRoute: typeof ProfilePortfolioRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-material/new': {
      id: '/find-material/new'
      path: '/new'
      fullPath: '/find-material/new'
      preLoaderRoute: typeof FindMaterialNewRouteImport
      parentRoute: typeof FindMaterialRoute
    }
    '/find-material/mine': {
      id: '/find-material/mine'
      path: '/mine'
      fullPath: '/find-material/mine'
      preLoaderRoute: typeof FindMaterialMineRouteImport
      parentRoute: typeof FindMaterialRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/admin/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/draws': {
      id: '/admin/draws'
      path: '/admin/draws'
      fullPath: '/admin/draws'
      preLoaderRoute: typeof AdminDrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$storeId/edit': {
      id: '/suppliers/$storeId/edit'
      path: '/edit'
      fullPath: '/suppliers/$storeId/edit'
      preLoaderRoute: typeof SuppliersStoreIdEditRouteImport
      parentRoute: typeof SuppliersStoreIdRoute
    }
    '/supplier/join/$token': {
      id: '/supplier/join/$token'
      path: '/supplier/join/$token'
      fullPath: '/supplier/join/$token'
      preLoaderRoute: typeof SupplierJoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/request/new': {
      id: '/rentals/request/new'
      path: '/rentals/request/new'
      fullPath: '/rentals/request/new'
      preLoaderRoute: typeof RentalsRequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new/$workerId': {
      id: '/projects/new/$workerId'
      path: '/projects/new/$workerId'
      fullPath: '/projects/new/$workerId'
      preLoaderRoute: typeof ProjectsNewWorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-notify': {
      id: '/api/public/telegram-notify'
      path: '/api/public/telegram-notify'
      fullPath: '/api/public/telegram-notify'
      preLoaderRoute: typeof ApiPublicTelegramNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FindMaterialRouteChildren {
  FindMaterialMineRoute: typeof FindMaterialMineRoute
  FindMaterialNewRoute: typeof FindMaterialNewRoute
}

const FindMaterialRouteChildren: FindMaterialRouteChildren = {
  FindMaterialMineRoute: FindMaterialMineRoute,
  FindMaterialNewRoute: FindMaterialNewRoute,
}

const FindMaterialRouteWithChildren = FindMaterialRoute._addFileChildren(
  FindMaterialRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfilePortfolioRoute: typeof ProfilePortfolioRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfilePortfolioRoute: ProfilePortfolioRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SuppliersStoreIdRouteChildren {
  SuppliersStoreIdEditRoute: typeof SuppliersStoreIdEditRoute
}

const SuppliersStoreIdRouteChildren: SuppliersStoreIdRouteChildren = {
  SuppliersStoreIdEditRoute: SuppliersStoreIdEditRoute,
}

const SuppliersStoreIdRouteWithChildren =
  SuppliersStoreIdRoute._addFileChildren(SuppliersStoreIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnnounceRoute: AnnounceRoute,
  FindMaterialRoute: FindMaterialRouteWithChildren,
  FindWorkerRoute: FindWorkerRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  InvitationsRoute: InvitationsRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  OnlineOrdersRoute: OnlineOrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AdminDrawsRoute: AdminDrawsRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  ListingsNewRoute: ListingsNewRoute,
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  RentalsRentalIdRoute: RentalsRentalIdRoute,
  RentalsNewRoute: RentalsNewRoute,
  StoryNewRoute: StoryNewRoute,
  StoryViewRoute: StoryViewRoute,
  SuperuserPanelRoute: SuperuserPanelRoute,
  SuppliersStoreIdRoute: SuppliersStoreIdRouteWithChildren,
  UsersUserIdRoute: UsersUserIdRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  ApiPublicTelegramNotifyRoute: ApiPublicTelegramNotifyRoute,
  ProjectsNewWorkerIdRoute: ProjectsNewWorkerIdRoute,
  RentalsRequestNewRoute: RentalsRequestNewRoute,
  SupplierJoinTokenRoute: SupplierJoinTokenRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
